from util.constants import *

class Config:
    # File paths
    BASE_DIR = BASE_DIR
    UPLOAD_FOLDER = PATH_INPUT.rstrip('/')
    OUTPUT_FOLDER = PATH_OUTPUT.rstrip('/')
    ORIGINALS_FOLDER = PATH_ORIGINALS.rstrip('/')
    
    # File configuration
    MAX_CONTENT_LENGTH = MAX_CONTENT_LENGTH
    ALLOWED_EXTENSIONS = ALLOWED_EXTENSIONS
    
    # Flask configuration
    DEBUG = DEBUG
    TESTING = TESTING
    SECRET_KEY = SECRET_KEY
    
    # CORS configuration
    CORS_ORIGINS = CORS_ORIGINS
    CORS_METHODS = CORS_METHODS
    CORS_ALLOW_HEADERS = CORS_ALLOW_HEADERS
    CORS_EXPOSE_HEADERS = CORS_EXPOSE_HEADERS
    CORS_SUPPORTS_CREDENTIALS = CORS_SUPPORTS_CREDENTIALS
    CORS_MAX_AGE = CORS_MAX_AGE
