version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./imagens/entrada:/app/imagens/entrada
      - ./imagens/saida:/app/imagens/saida
      - ./imagens/originais:/app/imagens/originais
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - HOST=0.0.0.0
      - PORT=8000
      - ONNXRUNTIME_DISABLE_GPU=1
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
